---
- name: Register ACI Fabric Nodes and Configure NTP
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: Register ACI Fabric Nodes
      cisco.aci.aci_fabric_node:
        host: "{{ aci.host }}"
        username: "{{ aci.username }}"
        password: "{{ aci.password }}"
        validate_certs: "{{ aci.validate_certs }}"
        serial: "{{ item.serial }}"
        node_id: "{{ item.id }}"
        switch: "{{ item.name }}"
        role: "{{ item.type }}"
        state: present
      loop: "{{ fabric_nodes }}"
      when: "'{{ item.id }}' in ['101', '201', '202', '102']"
      register: node_registration

    - name: Display node registration result
      debug:
        msg: "{{ node_registration.results }}"

    - name: Setup NTP Policy
      cisco.aci.aci_ntp_policy:
        host: "{{ aci.host }}"
        username: "{{ aci.username }}"
        password: "{{ aci.password }}"
        validate_certs: "{{ aci.validate_certs }}"
        name: my_ntp_policy
        admin_state: enabled
        state: present

    - name: Setup NTP Policy
      cisco.aci.aci_ntp_server:
        host: "{{ aci.host }}"
        username: "{{ aci.username }}"
        password: "{{ aci.password }}"
        validate_certs: "{{ aci.validate_certs }}"
        ntp_policy: my_ntp_policy
        ntp_server: "{{ ntp_server }}"
        preferred: true
        state: present
      register: ntp_configuration

    - name: Display NTP configuration result
      debug:
        msg: "{{ ntp_configuration }}"
